Logbook/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '',
  path_names: {sign_in: 'login', sign_up: 'registro'},
  controllers: {sessiones: 'users/sessions'}
 
  root 'home#index'

resources :myworks

resources :users do 
  resources :myworks
end

end

Logbook/app/models/home.rb
class Home < ActiveRecord::Base
    def to_param
        name
    end
end

Logbook/app/models/mywork.rb
class Mywork < ActiveRecord::Base
    belongs_to :user
end

Logbook/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    has_many :myworks
    validates :name, presence: true
end

Logbook/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up) << :name
    end
end

Logbook/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
   	if user_signed_in?
   		@mywork = current_user.myworks.new
   		render 'logbook'
   	else 
   	  render 'logbook'
		end
	end
end

Logbook/app/controllers/myworks_controller.rb
class MyworksController < ApplicationController
	before_action :authenticate_user!, only: :index

	def index
    @user = current_user
    @myworks = @user.myworks.all
  end

  def show
    @mywork = current_user.myworks.new
  end

  def new
    @user= User.find(params[:id])
    @mywork = current_user.myworks.new myworks_params
  end
  def destroy
    mywork = Mywork.destroy(params[:id])
    redirect_to myworks_path mywork.user
  end

  def create
    @user= User.find(params[:user_id])
    @mywork = current_user.myworks.new myworks_params

  if @mywork.save
    redirect_to myworks_path
  else
    render 'logbook'
  end
end

  def edit
    @user = current_user
    @mywork = Mywork.find(params[:id])
  end

  def update
    @mywork = Mywork.find(params[:id])
    if @mywork.update_attributes myworks_params
      redirect_to myworks_path(@mywork)
    end
  end

protected
  def myworks_params
    params.require(:mywork).permit(:markdown, :mTitle, :mDate)
  end
end

Logbook/app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

Logbook/app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only: :show
	
    def index
    	@user = User.find_by_name(params[:id])
      render 'home/logbook'
    end

    def update
    	render 'edit'
    end
end

Logbook/app/helpers/application_helper.rb
module ApplicationHelper
end

Logbook/app/helpers/home_helper.rb
module HomeHelper
end

Logbook/app/helpers/myworks_helper.rb
module MyworksHelper
end

Logbook/app/helpers/users_helper.rb
module UsersHelper
end

Logbook/app/views/home/logbook.html.erb
<header id="_header" class="format">
	<div class="centrary">
		<div class="titulo">
			<h1>logbook</h1>
			<p>create your own story</p>
		</div>
	</div>
	<nav id="_nav" class="nav_color texto_nav">
			

<% if user_signed_in? %>
	<div class="float_left">
		<p>Welcome <%= current_user.name %></p>
	</div>

	<div class="float_right">
		<p><%= link_to 'myworks', myworks_path %></p>
		<p><%= link_to 'Logout', destroy_user_session_path, method: 'DELETE' %></p>
	</div>
<% else %>
	<div class="float_right">
    	<a href="login" class="link_nav">log in</a>
		<a href="registro" class="link_nav">sign up</a>
		<a href="#footer" class="link_nav">about us</a>
	</div>
 <% end %>
		</nav>
	</header>	
<section class="botones">
	<ul>
		<li class="icons a-btn">
			<a href="#book">
				<span></span>
                <span class="cent_img"><%= image_tag("cerrado.png", :alt=>"cerrado")%></span>
                <span class="cent_txt">Book</span>
			</a>
		</li>

		<li class="icons a-btn">
			<a href="#port">
				<span></span>
                <span class="cent_img"><%= image_tag("lapiz.png", :alt=> "lapiz") %></span>
                <span class="cent_txt">Draw</span>
			</a>
		</li>
	
	</ul>
		<p class="textos_imp">Haz click sobre el opción que más te guste para comenzar tu propio proyecto!</p>
	</section>
	<section id="book" class="mainSection a_Sect">
	<aside class="menu sidebar sidef sidebar-menu-collapsed">
	    <nav class='sidebar sidef sidebar-menu-collapsed'>
	        <i id='justify-icon' class="fa fa-barcode"></i>
	 		<ul class='sidebar sidef sidebar-menu-collapsed'>
		        <li>
		          <a class='expandable'>
					<i class="fa fa-copyright"></i>
					<span id="helvetica" class="default classButtons expanded-element ">a b c</span>
		          </a>
		        </li>
		        <li>
		          <a class='expandable'>
					<i class="fa fa-comments"></i>
		            <span id="alex" class="classButtons expanded-element alex_regular ">a b c</span>
		          </a>
		        </li>
		        <li>
		          <a class='expandable'>
					<i class="fa fa-heart"></i> 
					<span id="kaushan" class="classButtons expanded-element kaushan_regular">a b c</span>
		          </a>
		      	</li>
	      </ul>			
	    </nav>
	</aside>
<% if !user_signed_in? %>
	<div class="link_login"><%= link_to 'haz LOGIN para guardar tus cambios!', new_user_session_path %></div>
	<textarea id="input" class="markDown mywork_markdown"></textarea>

<% else %>
	<div class="markDown">
	<%= form_for [current_user, @mywork] do |text| %>
		<%= text.text_area :markdown, :class => 'mywork_markdown' %>
		<input type='hidden' name='clase' value=resultClass[0]/>
	</div>	
		<%= text.submit "save" %>
	<% end %>
<% end %>
	<div id="preview" class="markDown"></div>

</section>

<section id="port" class="mainSection">
	<div id="proy_drawing" class="drawing_board"></div>
</section>

<footer id="footer" class="footer nav_color">
	<a href="#_header"><div class="box_foot verticaly"></div></a>
	<p class="brand">TEAMWORK</p>
	<ul><a href="http://estelapedrero.com">miguel angel herias</a>
		<li><a href="">&#xf099;</a></li>
		<li><a href="https://github.com/KiwiPlus">&#xf09b;</a></li>
		<li><a href="https://github.com/Franx0">&#xf0e1;</a></li>
	</ul>
	<ul><a href="https://soundcloud.com/franx0-1">francisco moya</a>
		<li><a href="https://twitter.com/Franxo06">&#xf099;</a></li>
		<li><a href="https://github.com/Franx0">&#xf09b;</a></li>
		<li><a href="https://www.linkedin.com/pub/fran-moya/57/876/346">&#xf0e1;</a></li>
	</ul>
	<ul><a href="http://estelapedrero.com">estela pedrero</a>
		<li><a href="http://twitter.com/sala_de_star">&#xf099;</a></li>
		<li><a href="https://github.com/estelapedrero">&#xf09b;</a></li>
		<li><a href="https://www.linkedin.com/in/estelapedrero">&#xf0e1;</a></li>
	</ul>
	<p class="brandcopy">&copylogbook</p>
</footer>

Logbook/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Logbook</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application', defer: true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Logbook/app/views/myworks/edit.html.erb
<header id="_header" class="format">
	<div class="centrary">
		<div class="titulo">
			<h1>logbook</h1>
			<p>create your own story</p>
		</div>
	</div>
	<nav id="_nav" class="nav_color texto_nav">
			

<% if user_signed_in? %>
	<div class="float_left">
	<p>Welcome <%= current_user.name %></p>
	</div>

	<div class="float_right">
		<p><%= link_to 'myworks', myworks_path %></p>
		<p><%= link_to 'Logout', destroy_user_session_path, method: 'DELETE' %></p>
	</div>
<% else %>
	<div class="float_right">
    <a href="login" class="link_nav">log in</a>
	<a href="registro" class="link_nav">sign up</a>
	<a href="#footer" class="link_nav">about us</a>
	</div>
 <% end %>
		</nav>
	</header>	
<section class="botones">
	<ul>
		<li class="icons a-btn">
			<a href="#book">
				<span></span>
                <span class="cent_img"><%= image_tag("cerrado.png", :alt=>"cerrado")%></span>
                <span class="cent_txt">Book</span>
			</a>
		</li>

		<li class="icons a-btn">
			<a href="#port">
				<span></span>
                <span class="cent_img"><%= image_tag("lapiz.png", :alt=> "lapiz") %></span>
                <span class="cent_txt">Draw</span>
			</a>
		</li>
	
	</ul>
		<p class="textos_imp">Haz click sobre el opción que más te guste para comenzar tu propio proyecto!</p>
	</section>
	<section id="book" class="mainSection a_Sect">
	<aside class="menu sidebar sidef sidebar-menu-collapsed">
	    <nav class='sidebar sidef sidebar-menu-collapsed'>
	        <i id='justify-icon' class="fa fa-barcode"></i>
	 		<ul class='sidebar sidef sidebar-menu-collapsed'>
		        <li>
		          <a class='expandable'>
					<i class="fa fa-copyright"></i>
					<span id="helvetica" class="default classButtons expanded-element ">a b c</span>
		          </a>
		        </li>
		        <li>
		          <a class='expandable'>
					<i class="fa fa-comments"></i>
		            <span id="alex" class="classButtons expanded-element alex_regular ">a b c</span>
		          </a>
		        </li>
		        <li>
		          <a class='expandable'>
					<i class="fa fa-heart"></i> 
					<span id="kaushan" class="classButtons expanded-element kaushan_regular">a b c</span>
		          </a>
		      	</li>
	      </ul>			
	    </nav>
	</aside>
<% if !user_signed_in? %>
	<div class="link_login"><%= link_to 'haz LOGIN para guardar tus cambios!', new_user_session_path %></div>
	<textarea id="input" class="markDown mywork_markdown"></textarea>

<% else %>
	<div class="markDown">
		<%= form_for [current_user, @mywork] do |text| %>
		<%= text.text_area :markdown, :class => 'mywork_markdown' %>
	</div>	
	<%= text.submit "save" %>
	<% end %>
<% end %>
	<div id="preview" class="markDown"></div>

</section>

<section id="port" class="mainSection b_Sect">
	<div id="proy_drawing" class="drawing_board"></div>
	<button class="drawing-board-control-download-button">Save</button>
</section>

<footer id="footer" class="footer nav_color">
	<a href="#_header"><div class="box_foot verticaly"></div></a>
	<p class="brand">TEAMWORK</p>
	<ul><a href="http://estelapedrero.com">miguel angel herias</a>
		<li><a href="">&#xf099;</a></li>
		<li><a href="https://github.com/KiwiPlus">&#xf09b;</a></li>
		<li><a href="https://github.com/Franx0">&#xf0e1;</a></li>
	</ul>
	<ul><a href="https://soundcloud.com/franx0-1">francisco moya</a>
		<li><a href="https://twitter.com/Franxo06">&#xf099;</a></li>
		<li><a href="https://github.com/Franx0">&#xf09b;</a></li>
		<li><a href="https://www.linkedin.com/pub/fran-moya/57/876/346">&#xf0e1;</a></li>
	</ul>
	<ul><a href="http://estelapedrero.com">estela pedrero</a>
		<li><a href="http://twitter.com/sala_de_star">&#xf099;</a></li>
		<li><a href="https://github.com/estelapedrero">&#xf09b;</a></li>
		<li><a href="https://www.linkedin.com/in/estelapedrero">&#xf0e1;</a></li>
	</ul>
	<p class="brandcopy">&copylogbook</p>
</footer>

Logbook/app/views/myworks/index.html.erb
<nav id="_nav" class="nav_color texto_nav">
	<div class="float_left">
	<p> myworks</p>
	<p><%= link_to 'editar perfil', edit_user_registration_path  %></p>
</div>
	<div class="float_right">
		
		<p><%= link_to 'new', root_path %></p>
	</div>
</nav>

<section class="myworks infoMyworks">
	<ul> 
		<% @myworks.each do |mywork| %>
		<li><%= mywork.markdown %>
		</li>
		<%= link_to 'edit', edit_mywork_path(mywork) %>
		<%= link_to 'delete', mywork_path(mywork), method: 'delete' %>
		<% end %>
		
	</ul>
</section>
<footer id="footer" class="footer nav_color">
	<a href="#_header"><div class="box_foot verticaly"></div></a>
	<p class="brand">TEAMWORK</p>
	<ul><a href="http://estelapedrero.com">miguel angel herias</a>
		<li><a href="">&#xf099;</a></li>
		<li><a href="https://github.com/KiwiPlus">&#xf09b;</a></li>
		<li><a href="https://github.com/Franx0">&#xf0e1;</a></li>
	</ul>
	<ul><a href="https://soundcloud.com/franx0-1">francisco moya</a>
		<li><a href="https://twitter.com/Franxo06">&#xf099;</a></li>
		<li><a href="https://github.com/Franx0">&#xf09b;</a></li>
		<li><a href="https://www.linkedin.com/pub/fran-moya/57/876/346">&#xf0e1;</a></li>
	</ul>
	<ul><a href="http://estelapedrero.com">estela pedrero</a>
		<li><a href="http://twitter.com/sala_de_star">&#xf099;</a></li>
		<li><a href="https://github.com/estelapedrero">&#xf09b;</a></li>
		<li><a href="https://www.linkedin.com/in/estelapedrero">&#xf0e1;</a></li>
	</ul>
	<p class="brandcopy">&copylogbook</p>
</footer>